import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState, useRef, useEffect } from "react";
export default function ChatInterface({ messages, onSend, loading, placeholder, title, isPublic, showQuickReplies, quickReplies, onQuickReply, aiName = "Dental AI Assistant", aiAvatar = "🤖", }) {
    const [input, setInput] = useState("");
    const endRef = useRef(null);
    useEffect(() => {
        endRef.current?.scrollIntoView({ behavior: "smooth" });
    }, [messages]);
    const handleSend = async () => {
        if (!input.trim() || loading)
            return;
        const msg = input.trim();
        setInput("");
        await onSend(msg);
    };
    const handleKey = (e) => {
        if (e.key === "Enter" && !e.shiftKey) {
            e.preventDefault();
            handleSend();
        }
    };
    const isAIMessage = (msg) => {
        return msg.role === "assistant" || msg.role === "ai";
    };
    return (_jsxs("div", { className: "flex flex-col h-full bg-white rounded-2xl border border-emerald-200 shadow-xl overflow-hidden", children: [_jsxs("div", { className: "flex items-center gap-3 px-5 py-4 border-b border-emerald-100 bg-gradient-to-r from-emerald-50 to-teal-50", children: [_jsx("div", { className: "w-14 h-14 rounded-xl bg-gradient-to-br from-emerald-400 to-teal-500 flex items-center justify-center text-white text-3xl shadow-lg", children: aiAvatar }), _jsxs("div", { children: [_jsx("h3", { className: "font-bold text-emerald-900 text-base", children: title || aiName }), _jsxs("div", { className: "flex items-center gap-1.5", children: [_jsx("div", { className: "w-2 h-2 rounded-full bg-emerald-500 animate-pulse" }), _jsxs("span", { className: "text-xs text-emerald-700 font-medium", children: ["Online \u2022 ", isPublic ? "Chế độ công khai" : "Chế độ riêng tư"] })] })] })] }), _jsxs("div", { className: "flex-1 overflow-y-auto p-4 space-y-4 bg-white", children: [messages.length === 0 && (_jsxs("div", { className: "flex flex-col items-center justify-center h-full text-center py-12", children: [_jsx("div", { className: "w-20 h-20 rounded-2xl bg-gradient-to-br from-emerald-400 to-teal-500 flex items-center justify-center text-white text-5xl mb-4 shadow-xl", children: aiAvatar }), _jsxs("p", { className: "font-display font-bold text-lg text-emerald-900", children: ["Xin ch\u00E0o! T\u00F4i l\u00E0 ", aiName] }), _jsx("p", { className: "text-sm text-emerald-700 mt-1 max-w-xs leading-relaxed", children: "T\u00F4i c\u00F3 th\u1EC3 gi\u00FAp b\u1EA1n v\u1EC1 s\u1EE9c kh\u1ECFe r\u0103ng mi\u1EC7ng, c\u00E1c d\u1ECBch v\u1EE5 nha khoa, v\u00E0 t\u01B0 v\u1EA5n ch\u0103m s\u00F3c r\u0103ng h\u00E0ng ng\u00E0y." }), showQuickReplies && quickReplies && quickReplies.length > 0 && (_jsxs("div", { className: "mt-5 w-full max-w-sm", children: [_jsx("p", { className: "text-xs text-emerald-500 font-medium mb-2", children: "B\u1EA1n c\u00F3 th\u1EC3 h\u1ECFi t\u00F4i:" }), _jsx("div", { className: "flex flex-wrap gap-2 justify-center", children: quickReplies.map((q, idx) => (_jsx("button", { onClick: () => onQuickReply?.(q), className: "text-xs bg-emerald-50 text-emerald-700 px-3 py-1.5 rounded-full border border-emerald-200 hover:bg-emerald-100 hover:border-emerald-300 transition cursor-pointer shadow-sm", children: q }, idx))) })] }))] })), messages.map((msg) => (_jsxs("div", { className: `flex ${msg.role === "user" ? "justify-end" : "justify-start"} gap-2`, children: [isAIMessage(msg) && (_jsx("div", { className: "w-7 h-7 rounded-lg bg-gradient-to-br from-emerald-400 to-teal-500 flex items-center justify-center text-white text-xs flex-shrink-0 mt-1 shadow-sm", children: aiAvatar })), _jsxs("div", { children: [_jsx("div", { className: msg.role === "user"
                                            ? "bg-gradient-to-r from-emerald-500 to-emerald-600 text-white rounded-2xl rounded-br-sm px-4 py-3 max-w-md shadow-md"
                                            : "bg-emerald-50 border border-emerald-100 text-emerald-900 rounded-2xl rounded-bl-sm px-4 py-3 max-w-md shadow-sm", style: { whiteSpace: "pre-line" }, children: _jsx("p", { className: "text-sm leading-relaxed", children: msg.content }) }), _jsx("p", { className: `text-[10px] mt-1 ${msg.role === "user" ? "text-right text-emerald-400" : "text-emerald-400"}`, children: new Date(msg.timestamp || new Date().toISOString()).toLocaleTimeString([], {
                                            hour: "2-digit",
                                            minute: "2-digit",
                                        }) })] }), msg.role === "user" && (_jsx("div", { className: "w-7 h-7 rounded-lg bg-emerald-100 flex items-center justify-center text-emerald-700 text-xs flex-shrink-0 mt-1 shadow-sm", children: "\uD83D\uDC64" }))] }, msg.id))), showQuickReplies && quickReplies && quickReplies.length > 0 && messages.length > 0 && (_jsx("div", { className: "flex flex-wrap gap-2", children: quickReplies.map((q, idx) => (_jsx("button", { onClick: () => onQuickReply?.(q), className: "text-xs bg-emerald-50 text-emerald-700 px-3 py-1.5 rounded-full border border-emerald-200 hover:bg-emerald-100 hover:border-emerald-300 transition cursor-pointer shadow-sm", children: q }, idx))) })), loading && (_jsxs("div", { className: "flex items-center gap-2", children: [_jsx("div", { className: "w-7 h-7 rounded-lg bg-gradient-to-br from-emerald-400 to-teal-500 flex items-center justify-center text-white text-xs shadow-sm", children: aiAvatar }), _jsxs("div", { className: "bg-emerald-50 border border-emerald-100 rounded-2xl rounded-bl-sm px-4 py-3 flex items-center gap-1.5 shadow-sm", children: [_jsx("div", { className: "w-2 h-2 rounded-full bg-emerald-400 animate-bounce", style: { animationDelay: "0ms" } }), _jsx("div", { className: "w-2 h-2 rounded-full bg-emerald-400 animate-bounce", style: { animationDelay: "150ms" } }), _jsx("div", { className: "w-2 h-2 rounded-full bg-emerald-400 animate-bounce", style: { animationDelay: "300ms" } })] })] })), _jsx("div", { ref: endRef })] }), _jsx("div", { className: "px-4 py-3 border-t border-emerald-100 bg-emerald-50/50", children: _jsxs("div", { className: "flex gap-2 items-end", children: [_jsx("textarea", { value: input, onChange: (e) => setInput(e.target.value), onKeyDown: handleKey, placeholder: placeholder || "Hỏi về sức khỏe răng miệng...", rows: 1, className: "resize-none flex-1 min-h-[44px] max-h-32 overflow-y-auto bg-white border border-emerald-200 rounded-2xl px-4 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-emerald-400 focus:border-emerald-400 placeholder-emerald-400 shadow-sm" }), _jsxs("button", { onClick: handleSend, disabled: !input.trim() || loading, className: `px-5 py-2.5 rounded-2xl flex items-center gap-2 flex-shrink-0 transition-all shadow-md font-medium text-sm ${!input.trim() || loading
                                ? "bg-emerald-200 text-emerald-400 cursor-not-allowed"
                                : "bg-gradient-to-r from-emerald-500 to-teal-500 text-white hover:from-emerald-600 hover:to-teal-600 active:scale-95"}`, children: [_jsx("svg", { viewBox: "0 0 24 24", fill: "none", stroke: "currentColor", strokeWidth: "2", className: "w-4 h-4", children: _jsx("path", { d: "M22 2L11 13M22 2L15 22l-4-9-9-4 20-7z" }) }), "G\u1EEDi"] })] }) })] }));
}
